spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lecture-management-db
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.xml
    enable: true
